### ISSUE TITLE
Sharepoint errrors and AzureADPreview module repeating install prompt

### ISSUE THREAD

**Issue by zildac** [soteria-security/365Inspect#15]
So I've just run this again for the first time in a few weeks, and I’m receiving the following errors re Sharepoint:

![image](https://user-images.githubusercontent.com/17178554/140060092-4dc08a64-55ba-4782-b207-6bf6e5944267.png)

I don't recall seeing the same output when I ran a while back. Also, the tool keeps prompting me to install the AzureADPreview module every time I run it, even though it appears to install when I select "Y" when prompted during the initial run.

**Comment by ThoughtContagion** [comment]
> So I've just run this again for the first time in a few weeks, and I’m receiving the following errors re Sharepoint:
> 
> ![image](https://user-images.githubusercontent.com/17178554/140060092-4dc08a64-55ba-4782-b207-6bf6e5944267.png)
> 
> I don't recall seeing the same output when I ran a while back. Also, the tool keeps prompting me to install the AzureADPreview module every time I run it, even though it appears to install when I select "Y" when prompted during the initial run.

I am not able to replicate either of these errors.
The SharePoint errors indicate that you are not authenticated to SharePoint - are you able to connect outside of the script?
The AzureAD module install also appears to work as expected. The install will force the installation for your user only and is not available machine-wide. 

![image](https://user-images.githubusercontent.com/88730003/140076756-c81ef985-853a-4842-a3cb-900d518b4a52.png)

When you run the tool initially, and the module installs, what happens if you were to run `Get-InstalledModule | Where-Object {$_.Name -like "AzureAD*"}`, do you still see the module as installed?

**Comment by zildac** [comment]
Thanks for the quick response. So I can login to SP in the two tenants I'm attempting to assess outside of the script, so that all seems good. Also, the output of Get-InstalledModule looks good:

![image](https://user-images.githubusercontent.com/17178554/140080244-4753509e-437d-43cc-806b-08816d64c922.png)

I may try on my Kali VM as it's likely a local issue given you can't reproduce it. Just not sure what has changed my side since I last ran the tool.

**Comment by ThoughtContagion** [comment]
No problem. as a heads-up, you may continue to run into issues/more issues if attempting to use a non-Windows OS. Some of those modules require the Windows OS authentication libraries to work properly.
I would also remove one of the AzureAD modules - preferably the AzureAD module, while keeping the Preview module. This will essentially "future proof" the modules required since some cmdlets are available only in the Preview module.
 
One other thing to keep in mind, if you have previously authenticated to an Azure resource using PowerShell, you may see errors when opening new sessions. I believe that Exchange and possibly SharePoint set limits on the number of concurrent sessions you may have in each module. We attempted to compensate for this with the ALREADY_AUTHED authentication option.

I'm going to close this issue, but feel free to reach back out if you have continued problems with the tool.

**Comment by zildac** [comment]
Many thanks. Yes, running under Kali produced a bunch of different errors. I'm going to clean up my W10 PowerShell install and start from the beginning, I think.  I'll also just use the AzureADPreview module as you suggest, sounds like a sensible approach. Good call re the concurrent sessions. I may try a manual auth and use the ALREADY_AUTHED option too. Thanks again for your help!

**Comment by ThoughtContagion** [comment]
Any time!
