### ISSUE TITLE
Excessive Privilege -> Not Using Microsoft Graph

### ISSUE THREAD

**Issue by za** [soteria-security/365Inspect#72]
**Is your feature request related to a problem? Please describe.**
As written in [README](https://github.com/soteria-security/365Inspect#necessary-privileges) it requires excessive privileges and sometimes it's not possible to have Administrator privilege.

**Describe the solution you'd like**
Can we not use Microsoft Graph and just use `ReadOnly` permission?

**Comment by ThoughtContagion** [comment]
Hi there,

We made the decision to leverage Microsoft Graph as the Azure AD and MSOL PowerShell modules are being deprecated by Microsoft. This allows us to utilize the newer, modern endpoints and ensure the tool does not stop functioning when the older modules are completely deprecated. 

Unfortunately, it is not possible to completely avoid the Global Administrator requirement. As noted in the README and the linked Microsoft documentation, the permissions required by Microsoft Graph require administrative consent. 

After the consent is granted, lesser permissions - Global Reader for example, may be able to use the tool.

Also, due to Microsoft limitations, it is not possible to avoid the requirement of SharePoint Administrator.

We are working on additional methods that may help mitigate some of the concerns surrounding the required permissions and the limitations imposed by Microsoft to access certain functions and endpoints necessary to return queried data.

**Comment by za** [comment]
Thanks for the explanation @ThoughtContagion . I am closing this issue now.
